parameters: {}
environment: {}
packages:
    - name: idaas
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: script
          binary: false
          main: "main.js"
          runtime: nodejs:default
          web: true
          websecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
